<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Pages extends Model {
    protected $table = 'pages';
    protected $fillable = ['content','title','project_id','user_id','parent_id'];

    public function project()
    {
        return $this->belongsTo(Project::class, 'project_id', 'id');
    }

    public function getSlug()
    {
        return $this->id;
    }

    public function getUrl()
    {
        return route('page.view', ['slug'=>$this->getSlug()]);
    }

    public function renderContent()
    {
        $parser = new \Parsedown();
        return $parser->text($this->content);
    }

    public function toArray()
    {
        $array = parent::toArray(); // TODO: Change the autogenerated stub
        $array['url'] = $this->getUrl();
        return $array;
    }
    
}