<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;
use Spatie\MediaLibrary\Media;

class Project extends Model implements HasMedia
{
    use HasMediaTrait;
    protected $table = 'projects';
    protected $fillable = ['title','user_id'];

    public function toArray()
    {
        $array = parent::toArray(); // TODO: Change the autogenerated stub
        $array['url'] = route('page.main', ['project_id'=>$this->id]);
        return $array;
    }

    public function pages()
    {
        return $this->hasMany(Pages::class, 'project_id', 'id');
    }

    public function getMediaFiles()
    {
        $files = [];
        $mediaFiles = Media::query()
            ->where('model_type', self::class)
            ->where('model_id', $this->id)
            ->get();
        foreach ($mediaFiles as $media) {
            $files[] = [
                'id' => $media->id,
                'name' => $media->name,
                'collection' => $media->collection_name,
                'thumb' => $media->getUrl()
            ];
        }
        return $files;
    }
}